# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  test:
    executor:
      name: node/default
      tag: '16.5.0'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
      - store_artifacts:
          path: coverage
  deploy:
    docker: 
      - image: arvindr226/alpine-ssh
    steps:
      - run: ssh -o StrictHostKeyChecking=no $USER@$SERVER 'projCatwalk/pull_and_deploy.sh'

workflows:
  "Run tests on PRs":
    jobs:
      - test
  "Deploy to machine":
    jobs:
      - deploy:
          filters:
            branches:
              only: release
